#!/usr/bin/ruby

require 'open-uri'
require 'json'

def get_description(summary)
  search_string = URI::encode summary
  address = "https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=#{search_string}&utf8=&format=json"

  open(address) {|page|
    puts JSON.parse(page.read)["query"]["search"][0]["snippet"].gsub /<.+?>/, ""
  }
end

ARGV.each do |a|
  puts get_description(a)
end

